djbook/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^test/', include('learn.urls', namespace='learn')),
    url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^admin/', include(admin.site.urls)),
]

learn/urls.py
from django.conf.urls import url, include
from learn import views

blogpatterns = [
    url(r'^upload/$', views.UploadFormView.as_view(), name='upload-form'),
    url(r'^static-page/$', views.StaticPageView.as_view()),
    url(r'^(?P<year>[0-9]{4})/$', views.year),
    url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$', views.month),
    url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]{2})/$', views.day),
    url(r'create/$', views.CreateBlogView.as_view(), name='create'),
    url(r'edit/(?P<pk>[0-9]+)/$', views.EditBlogView.as_view(), name='edit'),
    url(r'delete/(?P<pk>[0-9]+)/', views.DeleteBlogView.as_view(), name='delete'),
    url(r'^(?P<pk>[0-9]+)/$', views.BlogDetailView.as_view(), name='detail'),
    url(r'^contacts/$', views.ContactView.as_view(), name='contacts'),
    url(r'^download/$', views.download_csv_txt, name='download'),
    url(r'^pdfview/$', views.pdfview, name='pdfview'),
]

urlpatterns = [
    url(r'^$', views.EntryListView.as_view(), name='index'),
    url(r'^page/(?P<page>[0-9]+)/$', views.EntryListView.as_view(), name='paginate'),
    url(r'^blog/', include(blogpatterns)),
    url(r'^forms-test/$', views.FormsTestView.as_view(), name='forms_test'),
]

learn/models.py
from django.db import models
from django.utils import timezone
from learn import fields


class Person(models.Model):
    POSITIONS = (
        ('j_py', 'Python junior developer'),
        ('m_py', 'Python middle developer'),
        ('s_py', 'Python senior developer'),
        ('j_js', 'Javascript junior developer'),
        ('m_js', 'Javascript middle developer'),
        ('s_js', 'Javascript senior developer'),
        ('j_php', 'PHP junior developer'),
        ('m_php', 'PHP middle developer'),
        ('s_php', 'PHP senior developer'),
    )
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    company = models.ForeignKey('Company', blank=True, null=True, related_name='persons')
    position = models.CharField(max_length=255, choices=POSITIONS)
    recruitment = models.DateField(default=timezone.now)
    retirement = models.DateField(blank=True, null=True, name='leaving work')

    def __unicode__(self):
        return "%s %s" % (self.first_name, self.last_name)

    class Meta:
        db_table = 'person'
        verbose_name_plural = 'persons'


class PersonProxy(Person):
    class Meta:
        proxy = True


class Company(models.Model):
    name = models.CharField(max_length=75)
    description = models.TextField()
    founding_date = models.DateField(blank=True, null=True)

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        print "Add new company `%s`" % self.name
        super(Company, self).save(*args, **kwargs)

    def _is_old_company(self):
        return self.founding_date < timezone.datetime(2000, 1, 1).date()

    is_old_company = property(_is_old_company)

    class Meta:
        db_table = 'company'
        verbose_name_plural = 'companies'


class Tasks(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    deadline = models.DateField()
    allotted_time = models.IntegerField()
    elapsed_time = models.IntegerField()
    created = models.DateTimeField(default=timezone.now)
    closed = models.DateTimeField(blank=True, null=True)
    persons = models.ManyToManyField(Person, related_name='persons', db_table='tasks_to_persons')

    def __unicode__(self):
        return self.title

    class Meta:
        db_table = 'tasks'
        verbose_name_plural = 'tasks'


class PersonNote(Person):
    title = models.CharField(max_length=75)
    note = models.TextField(help_text="Note about person")

    def __unicode__(self):
        return self.title

    class Meta:
        db_table = 'person_note'
        verbose_name_plural = 'persons notes'


class HomerBlogManager(models.Manager):
    def get_queryset(self):
        return super(HomerBlogManager, self).get_queryset().filter(name__icontains='Homer')


class Blog(models.Model):
    name = models.CharField(max_length=100)
    tagline = models.TextField()
    image = models.ImageField(verbose_name='blog_logo', upload_to='blog_logo', blank=True)

    objects = models.Manager()
    homer = HomerBlogManager()

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse

        return reverse('learn:detail', kwargs={'blog_id': self.id})

    def delete(self, using=None):
        for entry in self.entry_set.all():
            entry.delete()

        return super(Blog, self).delete(using)

    class Meta:
        db_table = 'blog'
        ordering = ['name']


class Author(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()

    def __unicode__(self):
        return self.name

    class Meta:
        db_table = 'author'
        ordering = ['name']


class Entry(models.Model):
    blog = models.ForeignKey(Blog)
    headline = models.CharField(max_length=255)
    body_text = models.TextField()
    pub_date = models.DateField()
    mod_date = models.DateField()
    authors = models.ManyToManyField(Author)
    n_comments = models.IntegerField()
    n_pingbacks = models.IntegerField()
    rating = models.IntegerField()

    def __unicode__(self):
        return self.headline

    class Meta:
        db_table = 'blog_entry'
        ordering = ['-pub_date']

learn/forms.py
# -*- encoding: utf-8 -*-
from django import forms
from django.forms.utils import ErrorList
from django.utils.formats import mark_safe
import codecs


class UploadFileForm(forms.Form):
    title = forms.CharField()
    file = forms.FileField()


class ContactForm(forms.Form):
    name = forms.CharField(label='Your name')
    message = forms.CharField(label='Message', widget=forms.Textarea)

    def send(self):
        from djbook.settings import MEDIA_ROOT, os

        with codecs.open(os.path.join(MEDIA_ROOT, 'contacts.txt'), 'a+', encoding='utf-8') as f:
            message = u"Name: {name}\r\nMessage: {message}\r\n\r\n".format(**self.cleaned_data)
            f.write(message)

        return True


class TestForm(forms.Form):
    login = forms.CharField(max_length=70)
    password = forms.CharField(widget=forms.PasswordInput)


class NameForm(TestForm):
    from learn.fields import PhoneField
    from learn.widgets import LongTextInput

    required_css_class = 'form-required-field'
    your_name = forms.CharField(max_length=100, initial='Initial value')
    phone = PhoneField(label='Your Phone', widget=LongTextInput)

    def clean_phone(self):
        if '063' not in self.cleaned_data['phone']:
            raise forms.ValidationError('Wrong phone number. Phone number must contains %(mask)s', code='invalid',
                                        params={'mask': '063'})
        return self.cleaned_data


class BlogForm(forms.ModelForm):
    from learn.validators import homer_validator

    name = forms.CharField(label='Your name', widget=forms.Textarea(attrs={'cols': 40, 'rows': 2}),
                           validators=[homer_validator])

    class Meta:
        from learn.models import Blog

        model = Blog
        fields = '__all__'
        exclude = ['image']
        error_messages = {
            'tagline': {
                'required': 'Enter some words associated with this blog.',
            },
        }
        widgets = {
            'tagline': forms.TextInput(attrs={'size': 40})
        }

    def save(self, commit=True):
        if self.cleaned_data['name'] == 'Homer':
            raise forms.ValidationError('Homer, you don\'t have access to this operation.')
        return super(BlogForm, self).save(commit=commit)


# Custom errors class
class DivErrorList(ErrorList):
    def __unicode__(self):
        if not self:
            return ''
        else:
            return mark_safe(u'<div class="error">{0}</div>'.format("\n".join([u'<p>{0}</p>'.format(e) for e in self])))

learn/views.py
# coding: utf-8
from django.shortcuts import render, get_object_or_404, redirect, render_to_response
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponse, Http404, JsonResponse
from django.views.decorators.http import *
from django.views.decorators.gzip import gzip_page
from django.views.generic import TemplateView, ListView, DetailView, View
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView, TemplateResponseMixin, ContextMixin
from learn.models import Person, Entry, Blog, Author
from learn.forms import UploadFileForm, ContactForm, NameForm, DivErrorList, BlogForm
import datetime


def get_last_modified(request, *args, **kwargs):
    last_modified_date = None
    if 'blog_id' in kwargs:
        last_modified_date = datetime.datetime.today()

    return last_modified_date


@last_modified(get_last_modified)
@gzip_page
def detail(request, blog_id):
    return HttpResponse("Blog id: %s" % blog_id)


def year(request, *args, **kwargs):
    response = HttpResponse(u"<h1>Year: %(year)s</h1>" % kwargs)
    return response


def month(request, *args, **kwargs):
    return HttpResponse("Year: %(year)s<br>Month: %(month)s" % kwargs)


def day(request, *args, **kwargs):
    return HttpResponse("Year: %(year)s<br>Month: %(month)s<br>Day: %(day)s" % kwargs)


def download_csv(request):
    import csv

    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="blogs.csv"'

    blogs = list(Blog.objects.all().values())

    if not blogs:
        return HttpResponse('No blogs found')

    writer = csv.DictWriter(f=response, fieldnames=blogs[0].keys())
    writer.writeheader()
    for blog in blogs:
        for k, v in blog.iteritems():
            if type(v) is unicode:
                blog[k] = v.encode('utf-8')
        writer.writerow(blog)

    return response


def download_csv_txt(request):
    from django.shortcuts import render

    blogs = list(Blog.objects.all().values())

    if not blogs:
        return HttpResponse('No blogs found')

    for blog in blogs:
        for k, v in blog.iteritems():
            if type(v) is unicode:
                blog[k] = v.encode('utf-8')

    response = render(request, template_name='csv_template.txt', context={
        'head_row': ','.join(blogs[0].keys()),
        'rows': blogs
    })

    response['Content-Type'] = 'text/csv'
    response['Content-Disposition'] = 'attachment; filename="blogs.csv"'

    return response


# Generate pdf
def pdfview(request):
    from reportlab.pdfgen import canvas

    response = HttpResponse(content_type='application/pdf')

    c = canvas.Canvas(response, bottomup=False)
    t = c.beginText(100, 100)
    t.textLine("Blogs")

    c.drawText(t)

    c.showPage()
    c.save()

    return response


# Static page view

class StaticPageView(TemplateResponseMixin, ContextMixin, View):
    template_name = 'static_page.html'

    def get_context_data(self, **kwargs):
        from django.utils.lorem_ipsum import paragraphs

        context = super(StaticPageView, self).get_context_data(**kwargs)
        context['static_text'] = paragraphs(10)

        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)

        return self.render_to_response(context)


class TestManyDataMixin(object):
    def get_context_data(self, **kwargs):
        context = super(TestManyDataMixin, self).get_context_data(**kwargs)
        context['many_data_mixin'] = 'value'

        return context


class EntryListView(TestManyDataMixin, ListView):
    template_name = 'index.html'
    queryset = Entry.objects.all().prefetch_related('authors')
    context_object_name = 'entries'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(EntryListView, self).get_context_data(**kwargs)
        context['date'] = datetime.datetime.now().date()

        return context


class BlogDetailView(TestManyDataMixin, DetailView):
    model = Author
    template_name = 'blog_detail.html'
    context_object_name = 'author'

    def get_context_data(self, **kwargs):
        context = super(BlogDetailView, self).get_context_data(**kwargs)
        context['blogs'] = Blog.objects.filter(entry__authors=self.object).distinct()
        context['entries'] = Entry.objects.filter(authors=self.object)[:5]

        return context


# Contact form CBV
class ContactView(FormView):
    template_name = 'contacts.html'
    form_class = ContactForm
    success_url = '/test/'

    def form_valid(self, form):
        form.send()

        return super(ContactView, self).form_valid(form)


# CBV to model Blog
class TestMixin(object):
    def get_object(self, queryset=None):
        obj = super(TestMixin, self).get_object(queryset)
        print obj
        return obj


class CreateBlogView(CreateView):
    model = Blog
    template_name = 'blog_create.html'
    success_url = '/test/'

    def get_form(self, form_class=None):
        if form_class is None:
            from django import forms

            form_class = forms.modelform_factory(self.model, fields='__all__', exclude=['image'])
        return super(CreateView, self).get_form(form_class)

    def get_form_kwargs(self):
        kwargs = super(CreateBlogView, self).get_form_kwargs()
        kwargs['error_class'] = DivErrorList
        return kwargs


class EditBlogView(UpdateView):
    model = Blog
    fields = ['name', 'tagline', 'image']
    template_name = 'blog_edit.html'
    success_url = '/test/'


class DeleteBlogView(DeleteView):
    model = Blog
    success_url = '/test/'
    template_name = 'blog_delete.html'


class UploadFormView(FormView):
    template_name = 'upload_form.html'
    form_class = UploadFileForm

    def form_valid(self, form):
        from django.core.urlresolvers import reverse
        from djbook import settings

        self.success_url = reverse('learn:upload-form')

        if form.cleaned_data['title']:
            filename = settings.os.path.join(settings.MEDIA_ROOT, form.cleaned_data['title'])
        else:
            filename = settings.os.path.join(settings.MEDIA_ROOT, self.request.FILES['file'].name)

        with open(filename, 'wb+') as new_file:
            for chunk in self.request.FILES['file'].chunks():
                new_file.write(chunk)

        return super(UploadFormView, self).form_valid(form)


class FormsTestView(SuccessMessageMixin, FormView):
    template_name = 'forms-test.html'
    form_class = NameForm
    success_message = 'Form success'

    def form_valid(self, form):
        from django.core.urlresolvers import reverse

        self.success_url = reverse('learn:forms_test')
        return super(FormsTestView, self).form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(FormsTestView, self).get_form_kwargs()
        kwargs['auto_id'] = False
        kwargs['error_class'] = DivErrorList
        return kwargs

learn/templates/blog_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <style>
        .error { color: red; }
    </style>
</head>
<body>
    <h1>Create New Blog</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            <div>
                <div>{{ field.label_tag }}</div>
                <div>{{ field }}</div>
                {{ field.errors }}
            </div><br>
        {% endfor %}
        <input type="submit" value="Create">
    </form>
</body>
</html>

learn/templates/blog_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <h1>Delete {{ blog.name }}</h1>
    <form method="post">
        {% csrf_token %}
        <div>Are you sure delete `{{ blog.name }}` blog ?</div>
        <p><input type="submit" value="Delete"></p>
        <p><a href="#" onclick="history.back();return false;">Return</a></p>
    </form>
</body>
</html>

learn/templates/blog_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<h1>Welcome to {{ author.name }} page</h1>
<hr>
<p>You can view my blog list or my last blog entries. Enjoy!</p>
{% if blogs %}
    <h3>My blogs</h3>
    <ul>
        {% for blog in blogs %}
            <li>
                <a href="{% url 'learn:edit' blog.id %}">{{ blog.name }}</a>&nbsp;&nbsp;&nbsp;
                <span style="font-size: 12px;">
                    <a href="{% url 'learn:delete' blog.id %}">delete blog</a>
                </span>
            </li>
        {% endfor %}
    </ul>
{% endif %}

{% if entries %}
    <h3>My latest entries</h3>
    <ul>
        {% for entry in entries %}
            <li>{{ entry.headline }}</li>
        {% endfor %}
    </ul>
{% endif %}
</body>
</html>

learn/templates/blog_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <h1>Update {{ blog.name }}</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            <div>
                <div>{{ field.label_tag }}</div>
                <div>{{ field }}</div>
            </div><br>
        {% endfor %}
        <input type="submit" value="Edit">
    </form>
</body>
</html>

learn/templates/contacts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <h1>Contact Us</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {% for field in form %}
                <div>
                    <div>{{ field.label_tag }}</div>
                    {{ field }}
                    {% if field.errors %}
                        <p style="color: red; ">{{ field.errors.as_text }}</p>
                    {% endif %}
                </div><br>
            {% endfor %}
            <input type="submit" value="Send">
        </form>
    </div>
</body>
</html>

learn/templates/forms-test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <style>
        .error { color: red; }
        .form-required-field { color: #417690; }
        .form-required-field:after { content: "*"; }
    </style>
    {{ form.media }}
</head>
<body>
    <h2>Forms test template</h2>
    <p>
        {% for message in messages %}
            <h3>{{ message }}</h3>
        {% endfor %}
    </p>
    <div>
        <form action="/test/forms-test/" method="post">
            {% csrf_token %}
            {% for field in form %}
                <p>{{ field.label_tag }}</p>
                <p>{{ field }}</p>
                {{ field.errors }}
            {% endfor %}
            <input type="submit" value="Submit">
        </form>
    </div>
</body>
</html>

learn/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <h2>Today: {{ date }}</h2>
    <h4>
        <a href="{% url 'learn:download' %}">Download blogs list</a> or
        <a href="{% url 'learn:pdfview' %}">Show blogs in pdf</a>
    </h4>
    {% for entry in entries %}
        <div>
            <p><b>Author: </b>
                {% for author in entry.authors.all %}
                    <a href="{% url 'learn:detail' author.pk  %}">{{ author.name }}</a>
                {% endfor %}
                &nbsp;&nbsp;&nbsp;{{ entry.pub_date }}</p>
            <p>
                <b>{{ entry.headline }}</b><br>
                {{ entry.body_text }}
            </p>
        </div>
        <hr>
    {% endfor %}
    {% if is_paginated %}
        <div>
            <p>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</p>
            <div>
                {% if page_obj.has_previous %}
                    <a href="{% url 'learn:paginate' page_obj.previous_page_number %}">previous</a>&nbsp;&nbsp;&nbsp;
                {% endif %}
                {% if page_obj.has_next %}
                    <a href="{% url 'learn:paginate' page_obj.next_page_number %}">next</a>
                {% endif %}
            </div>
        </div>
    {% endif %}
</body>
</html>

learn/templates/static_page.html
{% load learn_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <style>
        .marked {
            color: #417690;
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <h1>Static page</h1>
    <div style="float: left; width: 200px; ">
        {% posts_list %}
    </div>
    <div style="float: left; width: 75%">
        <ol>
            {% for p in static_text %}
                <li class="{% cycle 'odd' 'even' %}">{{ p|mark_sub:'Lorem ipsum' }}</li>
            {% endfor %}
        </ol>
    </div>
    <div style="clear: both;">{% counter %}</div>
    {% register_var as assignment_tag_var %}
    {{ assignment_tag_var }}
    {% comment 'Output list by filter' %}
    <ol>
        {{ static_text|unordered_list }}
    </ol>
    {% endcomment %}
    {% comment 'test filter' %}
    {{ '1000'|filesizeformat }}
    {% endcomment %}
</body>
</html>

learn/templates/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<h1>Upload File</h1>
<form method="post", enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
        <div>
            {{ field.label }}<br>
            {{ field }}
            <div style="color: red;">{{ field.errors }}</div>
        </div>
        <br><br>
    {% endfor %}
    <input type="submit" value="Upload">
</form>
</body>
</html>

learn/templates/upload_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<h1>Upload File</h1>
<form action="{% url 'learn:upload-form' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
        <div>
            {{ field.label }}<br>
            {{ field }}
            <div style="color: red;">{{ field.errors }}</div>
        </div>
        <br><br>
    {% endfor %}
    <input type="submit" value="Upload">
</form>
</body>
</html>